#!/usr/bin/env bash

set -euxo pipefail

kubectl rollout status statefulsets.apps gitea --timeout=60s || printf "I expected an gitea statefulset"  

kubectl get svc gitea-http  || printf "I expected an gitea-http deployment"  

kubectl wait --for=condition=complete --timeout=180s -n drone job/workshop-setup
