#!/usr/bin/env bash

set -euxo pipefail

# sanity checks
printf "\nRegistry Sanity Checks\n"

# Docker push
docker pull gcr.io/google-samples/hello-app:1.0
docker tag gcr.io/google-samples/hello-app:1.0 "localhost:$REGISTRY_PORT/hello-app:1.0"
docker push "localhost:$REGISTRY_PORT/hello-app:1.0"

# Kubectl
kubectl_client_version=$(kubectl version --output=json | jq  -r '.clientVersion | .major + "." + .minor')

if [[ ! $K3S_VERSION =~ $kubectl_client_version ]]
then
  printf "kubectl version '%s' is not matching '%s'"  "$kubectl_client_version" "${K3S_VERSION%[+-]*}" 
  exit 1
fi

kubectl create deployment hello-server --image="k3d-${REGISTRY_NAME}:$REGISTRY_PORT/hello-app:1.0"
kubectl rollout status deployment.apps/hello-server --timeout=30s
kubectl delete deployment.apps/hello-server