#!/usr/bin/env bash

set -euo pipefail

helm repo add argo https://argoproj.github.io/argo-helm
helm repo update

GITEA_HTTP_CLUSTER_IP=$(kubectl get -n default svc gitea-http -ojsonpath='{.spec.clusterIP}'
)
export GITEA_HTTP_CLUSTER_IP

[[ -n "$GITEA_HTTP_CLUSTER_IP" ]] && envsubst < "$GITOPS_HOME/helm_vars/argocd/values.yaml" | helm upgrade --install argocd argo/argo-cd \
  --create-namespace \
  --namespace=argocd \
  --values - \
  --wait

envsubst < "$GITOPS_HOME/helm_vars/core/values.tpl.yaml" > "$GITOPS_HOME/helm_vars/core/values.yaml"

# Add/Update origin
pushd "$GITOPS_HOME"
git config --global user.email "${GITEA_USER}@example.com"
git config --global user.name "${GITEA_USER}"
PUSH_GITEA_URL="http://${GITEA_USER}:user-01%40123@host.docker.internal:30950"

git add .
git commit -a -m "Init Gitops"
git push "${PUSH_GITEA_URL}/${GITEA_USER}/gitops-on-k3s.git" "${GITEA_GITOPS_CORE_REPO_VERSION}"
popd 

envsubst < "$GITOPS_HOME/k8s/core/app.yaml" | kubectl apply -f -

# argocd login --plaintext "host.docker.internal:30080" \
#   --insecure \
#   --username "${ARGO_ADMIN_USER}" \
#   --password="${ARGO_ADMIN_PASSWORD}"

# argocd app sync --core --plaintext --assumeYes --timeout=600 gitops-on-k3s-apps

sleep 15

# wait for drone to be ready
kubectl rollout status -n drone deploy/drone --timeout=120s

# Patching Gitea with Drone IP for resolving
DRONE_SERVICE_IP="$(kubectl get svc -n drone drone -ojsonpath='{.spec.clusterIP}')"
export DRONE_SERVICE_IP
kubectl patch statefulset gitea -n default --patch "$(envsubst < "$GITOPS_HOME/k8s/gitea/patch.json")"

kubectl rollout status -n default statefulset gitea --timeout=120s