apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: drone
resources:
- https://raw.githubusercontent.com/kameshsampath/drone-tutorial-gitea-helper/main/manifests/install.yaml

patches:
- path: workshop-config-patch.yaml
  target:
    kind: ConfigMap